name: ai-travel-agents
services:
  tool-customer-query:
    container_name: tool-customer-query
    build: ./tools/customer-query
    ports:
      - "5001:8080"
    environment:
      - OTEL_SERVICE_NAME=tool-customer-query
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889

  tool-destination-recommendation:
    container_name: tool-destination-recommendation
    build: ./tools/destination-recommendation
    ports:
      - "5002:8080"

  tool-itinerary-planning:
    container_name: tool-itinerary-planning
    build: ./tools/itinerary-planning
    ports:
      - "5003:8000"

  tool-code-evaluation:
    container_name: tool-code-evaluation
    build: ./tools/code-evaluation
    ports:
      - "5004:5000"

  tool-model-inference:
    container_name: tool-model-inference
    build: ./tools/model-inference
    ports:
      - "5005:5000"
  
  tool-web-search:
    container_name: tool-web-search
    build: ./tools/web-search
    ports:
      - "5006:5000"
      
  tool-echo-ping:
    container_name: tool-echo-ping
    build: ./tools/echo-ping
    ports:
      - "5007:5000"
    environment:
      - OTEL_SERVICE_NAME=tool-echo-ping
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_HEADERS=x-otlp-header=header-value

  web-api:
    container_name: web-api
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - tool-customer-query
      - tool-destination-recommendation
      - tool-itinerary-planning
      - tool-code-evaluation
      - tool-model-inference
      - tool-web-search
      - tool-echo-ping
    env_file: 
      - "./api/.env.dev"
      - "./api/.env.docker" # override .env with .env.docker

  web-ui:
    container_name: web-ui
    build: ./ui
    ports:
      - "4200:4200"
    depends_on:
      - web-api

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - 18888:18888
      - 4317:18889
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
